# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401
from swagger_server.config import db
from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Banner(Model, db.Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    app_code = db.Column(db.String(20), primary_key=True)
    date_start = db.Column(db.DateTime(), primary_key=True)
    date_finish = db.Column(db.DateTime(), nullable=False)
    msg = db.Column(db.Text(), nullable=False)

    swagger_types = {
        'app_code': str,
        'date_start': datetime,
        'date_finish': datetime,
        'msg': str
    }

    attribute_map = {
        'app_code': 'app_code',
        'date_start': 'date_start',
        'date_finish': 'date_finish',
        'msg': 'msg'
    }

    def __init__(self, app_code: str = None, date_start: datetime = None,
                 date_finish: datetime = None, msg: str = None):  # noqa: E501
        """Banner - a model defined in Swagger

        :param app_code: The app_code of this Banner.  # noqa: E501
        :type app_code: str
        :param date_start: The date_start of this Banner.  # noqa: E501
        :type date_start: datetime
        :param date_finish: The date_finish of this Banner.  # noqa: E501
        :type date_finish: datetime
        :param msg: The msg of this Banner.  # noqa: E501
        :type msg: str
        """

        self.app_code = app_code
        self.date_start = date_start
        self.date_finish = date_finish
        self.msg = msg

    @classmethod
    def from_dict(cls, dikt) -> 'Banner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Banner of this Banner.  # noqa: E501
        :rtype: Banner
        """
        return util.deserialize_model(dikt, cls)
